apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: one-by-one
  annotations:
    description: ""
spec:
  triggerEnvironment: develop
  steps:
    - environment: prod-eu
      dependsOn:
        - develop
      policy:
        action: commit
    - environment: prod-eu2
      dependsOn:
        - prod-eu
      policy:
        action: commit
