gitops-runtime:
  global:
    codefresh:
      accountId: 68401e38bf11f3ed85cd17b2
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
      isConfigurationRuntime: true
